CREATE DATABASE MARKET
USE MARKET

CREATE TABLE PRODUCTS
(
ID INT,
NAME NVARCHAR(30),
BRAND NVARCHAR(30)
) 
DROP TABLE PRODUCTS
ALTER TABLE PRODUCTS 
ALTER COLUMN NAME NVARCHAR(20)
ALTER TABLE PRODUCTS 
ADD PRICE INT

INSERT INTO PRODUCTS
VALUES
(1,'IPHONE11','APPLE',2100),
(2, 'IPHONE12','APPLE',2200),
(3,'IPHONE13','APPLE',2300),
(4,'IPHONE14','APPLE',2400),
(5,'IPHONE15','APPLE',2500),
(6,'IPHONE16','APPLE',2600),
(7,'IPHONE17','APPLE',2700)

SELECT * FROM PRODUCTS
SELECT * FROM PRODUCTS

WHERE PRICE>=2300

SELECT * FROM PRODUCTS 
WHERE NAME LIKE '%E%' AND PRICE>2500

SELECT * FROM PRODUCTS 

WHERE PRICE BETWEEN 2300 AND 2600

UPDATE PRODUCTS 

SET PRICE=2400
WHERE PRICE<=2400

UPDATE PRODUCTS 
SET PRICE=2100
WHERE ID IN (1,2,3)

ALTER TABLE PRODUCTS

ALTER COLUMN NAME NVARCHAR(25) NOT NULL

ALTER TABLE PRODUCTS
DROP COLUMN BRAND
SELECT * FROM PRODUCTS
ALTER TABLE PRODUCTS
ADD BRAND NVARCHAR(25) NOT NULL CHECK(LEN(BRAND)>=2)


 